"""FRED series configuration for labor market data ingestion."""

FRED_SERIES = [
    {
        "series_id": "PAYEMS",
        "name": "Total Nonfarm Payrolls",
        "frequency": "monthly",
        "units": "Thousands of Persons",
        "category": "employment",
    },
    {
        "series_id": "UNRATE",
        "name": "Unemployment Rate",
        "frequency": "monthly",
        "units": "Percent",
        "category": "unemployment",
    },
    {
        "series_id": "CIVPART",
        "name": "Labor Force Participation Rate",
        "frequency": "monthly",
        "units": "Percent",
        "category": "employment",
    },
    {
        "series_id": "CES0500000003",
        "name": "Average Hourly Earnings (Private)",
        "frequency": "monthly",
        "units": "Dollars per Hour",
        "category": "wages",
    },
    {
        "series_id": "JTSJOL",
        "name": "Job Openings (JOLTS)",
        "frequency": "monthly",
        "units": "Thousands",
        "category": "job_openings",
    },
    {
        "series_id": "ICSA",
        "name": "Initial Jobless Claims",
        "frequency": "weekly",
        "units": "Number",
        "category": "claims",
    },
    {
        "series_id": "U6RATE",
        "name": "U-6 Underemployment Rate",
        "frequency": "monthly",
        "units": "Percent",
        "category": "unemployment",
    },
    {
        "series_id": "EMRATIO",
        "name": "Employment-Population Ratio",
        "frequency": "monthly",
        "units": "Percent",
        "category": "employment",
    },
    # --- Industry Employment (BLS CES) ---
    {
        "series_id": "MANEMP",
        "name": "All Employees: Manufacturing",
        "frequency": "monthly",
        "units": "Thousands of Persons",
        "category": "industry",
    },
    {
        "series_id": "USCONS",
        "name": "All Employees: Construction",
        "frequency": "monthly",
        "units": "Thousands of Persons",
        "category": "industry",
    },
    {
        "series_id": "USEHS",
        "name": "All Employees: Education and Health Services",
        "frequency": "monthly",
        "units": "Thousands of Persons",
        "category": "industry",
    },
    {
        "series_id": "USPBS",
        "name": "All Employees: Professional and Business Services",
        "frequency": "monthly",
        "units": "Thousands of Persons",
        "category": "industry",
    },
    {
        "series_id": "USLAH",
        "name": "All Employees: Leisure and Hospitality",
        "frequency": "monthly",
        "units": "Thousands of Persons",
        "category": "industry",
    },
    {
        "series_id": "USGOVT",
        "name": "All Employees: Government",
        "frequency": "monthly",
        "units": "Thousands of Persons",
        "category": "industry",
    },
    {
        "series_id": "USTRADE",
        "name": "All Employees: Retail Trade",
        "frequency": "monthly",
        "units": "Thousands of Persons",
        "category": "industry",
    },
    {
        "series_id": "USWTRADE",
        "name": "All Employees: Wholesale Trade",
        "frequency": "monthly",
        "units": "Thousands of Persons",
        "category": "industry",
    },
    {
        "series_id": "USINFO",
        "name": "All Employees: Information",
        "frequency": "monthly",
        "units": "Thousands of Persons",
        "category": "industry",
    },
    {
        "series_id": "USFIRE",
        "name": "All Employees: Financial Activities",
        "frequency": "monthly",
        "units": "Thousands of Persons",
        "category": "industry",
    },
    {
        "series_id": "USMINE",
        "name": "All Employees: Mining and Logging",
        "frequency": "monthly",
        "units": "Thousands of Persons",
        "category": "industry",
    },
    {
        "series_id": "CES4300000001",
        "name": "All Employees: Transportation and Warehousing",
        "frequency": "monthly",
        "units": "Thousands of Persons",
        "category": "industry",
    },
]

FRED_BASE_URL = "https://api.stlouisfed.org/fred/series/observations"
DEFAULT_OBSERVATION_START = "2000-01-01"
