"""Series metadata, display names, and color palette."""

SERIES_META = {
    "PAYEMS": {
        "display_name": "Total Nonfarm Payrolls",
        "short_name": "Nonfarm Payrolls",
        "units": "Million",
        "format": ",.1f",
        "change_format": "+,.1f",
        "display_divisor": 1000,
        "category": "employment",
        "color": "#1f77b4",
    },
    "UNRATE": {
        "display_name": "Unemployment Rate",
        "short_name": "Unemployment (U-3)",
        "units": "%",
        "format": ".1f",
        "change_format": "+.1f",
        "category": "unemployment",
        "color": "#d62728",
    },
    "CIVPART": {
        "display_name": "Labor Force Participation Rate",
        "short_name": "Participation Rate",
        "units": "%",
        "format": ".1f",
        "change_format": "+.1f",
        "category": "employment",
        "color": "#2ca02c",
    },
    "CES0500000003": {
        "display_name": "Average Hourly Earnings (Private)",
        "short_name": "Avg. Hourly Earnings",
        "units": "$/hr",
        "format": ",.2f",
        "change_format": "+,.2f",
        "category": "wages",
        "color": "#ff7f0e",
    },
    "JTSJOL": {
        "display_name": "Job Openings (JOLTS)",
        "short_name": "Job Openings",
        "units": "Million",
        "format": ",.1f",
        "change_format": "+,.1f",
        "display_divisor": 1000,
        "category": "job_openings",
        "color": "#9467bd",
    },
    "ICSA": {
        "display_name": "Initial Jobless Claims",
        "short_name": "Jobless Claims",
        "units": "",
        "format": ",.0f",
        "change_format": "+,.0f",
        "category": "claims",
        "color": "#8c564b",
    },
    "U6RATE": {
        "display_name": "U-6 Underemployment Rate",
        "short_name": "Underemployment (U-6)",
        "units": "%",
        "format": ".1f",
        "change_format": "+.1f",
        "category": "unemployment",
        "color": "#e377c2",
    },
    "EMRATIO": {
        "display_name": "Employment-Population Ratio",
        "short_name": "Emp-Pop Ratio",
        "units": "%",
        "format": ".1f",
        "change_format": "+.1f",
        "category": "employment",
        "color": "#17becf",
    },
    # --- Industry Employment ---
    "MANEMP": {
        "display_name": "All Employees: Manufacturing",
        "short_name": "Manufacturing",
        "units": "Thousands",
        "format": ",.0f",
        "change_format": "+,.0f",
        "category": "industry",
        "color": "#1f77b4",
    },
    "USCONS": {
        "display_name": "All Employees: Construction",
        "short_name": "Construction",
        "units": "Thousands",
        "format": ",.0f",
        "change_format": "+,.0f",
        "category": "industry",
        "color": "#ff7f0e",
    },
    "USEHS": {
        "display_name": "All Employees: Education & Health Services",
        "short_name": "Education & Health",
        "units": "Thousands",
        "format": ",.0f",
        "change_format": "+,.0f",
        "category": "industry",
        "color": "#2ca02c",
    },
    "USPBS": {
        "display_name": "All Employees: Professional & Business Services",
        "short_name": "Prof. & Business Svc.",
        "units": "Thousands",
        "format": ",.0f",
        "change_format": "+,.0f",
        "category": "industry",
        "color": "#d62728",
    },
    "USLAH": {
        "display_name": "All Employees: Leisure & Hospitality",
        "short_name": "Leisure & Hospitality",
        "units": "Thousands",
        "format": ",.0f",
        "change_format": "+,.0f",
        "category": "industry",
        "color": "#9467bd",
    },
    "USGOVT": {
        "display_name": "All Employees: Government",
        "short_name": "Government",
        "units": "Thousands",
        "format": ",.0f",
        "change_format": "+,.0f",
        "category": "industry",
        "color": "#8c564b",
    },
    "USTRADE": {
        "display_name": "All Employees: Retail Trade",
        "short_name": "Retail Trade",
        "units": "Thousands",
        "format": ",.0f",
        "change_format": "+,.0f",
        "category": "industry",
        "color": "#e377c2",
    },
    "USWTRADE": {
        "display_name": "All Employees: Wholesale Trade",
        "short_name": "Wholesale Trade",
        "units": "Thousands",
        "format": ",.0f",
        "change_format": "+,.0f",
        "category": "industry",
        "color": "#7f7f7f",
    },
    "USINFO": {
        "display_name": "All Employees: Information",
        "short_name": "Information",
        "units": "Thousands",
        "format": ",.0f",
        "change_format": "+,.0f",
        "category": "industry",
        "color": "#bcbd22",
    },
    "USFIRE": {
        "display_name": "All Employees: Financial Activities",
        "short_name": "Financial Activities",
        "units": "Thousands",
        "format": ",.0f",
        "change_format": "+,.0f",
        "category": "industry",
        "color": "#17becf",
    },
    "USMINE": {
        "display_name": "All Employees: Mining & Logging",
        "short_name": "Mining & Logging",
        "units": "Thousands",
        "format": ",.0f",
        "change_format": "+,.0f",
        "category": "industry",
        "color": "#aec7e8",
    },
    "CES4300000001": {
        "display_name": "All Employees: Transportation & Warehousing",
        "short_name": "Transport. & Warehousing",
        "units": "Thousands",
        "format": ",.0f",
        "change_format": "+,.0f",
        "category": "industry",
        "color": "#ffbb78",
    },
}

# Ordered list for overview page
OVERVIEW_SERIES = ["PAYEMS", "UNRATE", "CIVPART", "CES0500000003", "JTSJOL", "ICSA", "U6RATE", "EMRATIO"]

# Which direction is "good" for each series (used for coloring changes)
# True = higher is better, False = lower is better
HIGHER_IS_BETTER = {
    "PAYEMS": True,
    "UNRATE": False,
    "CIVPART": True,
    "CES0500000003": True,
    "JTSJOL": True,
    "ICSA": False,
    "U6RATE": False,
    "EMRATIO": True,
}

# Ordered list for industry employment page (descending by typical employment level)
INDUSTRY_SERIES = [
    "USEHS", "USPBS", "USGOVT", "USLAH", "USTRADE", "MANEMP",
    "USCONS", "USFIRE", "CES4300000001", "USWTRADE", "USINFO", "USMINE",
]
